---
- name: Update dan Patch Linux
  hosts: all
  gather_facts: yes
  become: yes
  
  tasks:
    - name: Wait for system to be ready
      wait_for_connection:
        timeout: 60
    
    - name: Update repository cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Upgrade semua paket (skip yang conflict/downgrade)
      apt:
        upgrade: safe
        autoremove: yes
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
      async: 3600
      poll: 10
      register: apt_upgrade
    
    - name: Tampilkan hasil upgrade
      debug:
        msg: "Upgrade completed successfully"
      when: apt_upgrade.changed
